HORIZONTAL_RESOLUTION = 1600
VERTICAL_RESOLUTION = 900
FULLSCREEN = False

TILE_SIZE = 64
WORLD_SIZE = 40
CAMERA_SPEED = 12
MOISTURE_MULTIPLIER = 20
ELECTRICITY_MULTIPLIER = 16
WATER_PUMP_COST_MULTIPLIER = 0.3
SOLAR_PANEL_CLEANING_COST_MULTIPLIER = 0.15
TEXT_SIZE = 28 * VERTICAL_RESOLUTION/1080
